services:
  - type: web
    name: whatsapp-wrapped-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://whatsapp-wrapped-delta.vercel.app
      - key: WEBSITE_URL
        value: https://whatsapp-wrapped-delta.vercel.app 