services:
  - type: web
    name: whatsapp-wrapped-backend
    env: python
    runtime: python3
    region: frankfurt
    buildCommand: |
      curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 &&
      python3.11 -m venv .venv &&
      . .venv/bin/activate &&
      apt-get update -y && 
      apt-get install -y python3.11-dev python3-pip python3-setuptools \
        libjpeg-dev zlib1g-dev libfreetype6-dev \
        python3-pil python3-pil.imagetk &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: .venv/bin/gunicorn api.application:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: RENDER
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://whatsapp-wrapped-delta.vercel.app
      - key: WEBSITE_URL
        value: https://whatsapp-wrapped-delta.vercel.app
    healthCheckPath: /health
    autoDeploy: true 