services:
  - type: web
    name: whatsapp-wrapped-backend
    env: python
    buildCommand: |
      apt-get update -y && 
      apt-get install -y python3-dev python3-pip python3-setuptools libjpeg-dev zlib1g-dev &&
      pip install -r requirements.txt
    startCommand: gunicorn api.application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: RENDER
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://whatsapp-wrapped-delta.vercel.app
      - key: WEBSITE_URL
        value: https://whatsapp-wrapped-delta.vercel.app 