services:
  - type: web
    name: whatsapp-wrapped-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: api.application
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: "https://your-frontend-url.vercel.app"  # Update this after Vercel deployment 