services:
  - type: web
    name: whatsapp-wrapped-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: RENDER
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://whatsapp-wrapped-delta.vercel.app
      - key: WEBSITE_URL
        value: https://whatsapp-wrapped-delta.vercel.app 
      - key: DATABASE_URL
          value: postgresql://whatsapp_wrapped_db_user:1zKIgj34gWughTg1dGWqJGK3zqxryZrN@dpg-d2mrhfbipnbc73f8pa1g-a/whatsapp_wrapped_db